export const SYSTEM_EVENT_TYPES = [
  'auth.login.succeeded', 'auth.login.failed', 'auth.token.invalid', 'auth.token.expired',
  'auth.api_key.invalid', 'auth.api_key.inactive', 'access.denied',
  'access.cross_tenant_rejected', 'rate_limit.exceeded', 'request.validation_rejected',
  'tenant.switched', 'tenant.created', 'tenant.updated', 'tenant.deactivated',
  'user.created', 'user.updated', 'user.activated', 'user.deactivated',
  'user.tenant_assigned', 'user.tenant_removed', 'user.role_changed',
  'user.permission_changed', 'sync.started', 'sync.batch.started',
  'sync.batch.completed', 'sync.retrying', 'sync.completed', 'sync.failed',
  'sync.cancel_requested', 'sync.cancelled', 'sync.interrupted',
  'sync.watermark.updated', 'sync.failed_batch.persisted',
  'sync_command.queued', 'sync_command.claimed', 'sync_command.started',
  'sync_command.progress', 'sync_command.completed', 'sync_command.failed',
  'sync_command.cancel_requested', 'sync_command.cancelled', 'sync_command.lease_expired',
  'sync_command.interrupted',
  'inventory.source.selected', 'inventory.source.conflict', 'inventory.source.unavailable',
  'inventory.zero_snapshot.confirmed', 'inventory.zero_snapshot.rejected',
  'inventory.snapshot.staged', 'inventory.snapshot.activated',
  'inventory.product_stock.reconciled', 'inventory.stock_mismatch_detected',
  'backend.started', 'backend.stopping', 'backend.request.failed',
  'database.connected', 'database.connection_failed',
  'redis.connected', 'redis.connection_failed', 'cache.invalidated',
  'cache.invalidation_failed', 'materialized_view.refresh_started',
  'materialized_view.refresh_completed', 'materialized_view.refresh_failed',
  'migration.started', 'migration.completed', 'migration.failed',
  'deployment.started', 'deployment.completed', 'agent.registered',
  'agent.heartbeat', 'agent.online', 'agent.degraded', 'agent.offline',
  'service.started', 'service.stopping', 'service.stopped', 'service.crashed',
  'scheduler.started', 'scheduler.paused', 'scheduler.resumed',
  'jtl_connection.connected', 'jtl_connection.failed',
  'backend_connection.connected', 'backend_connection.failed',
  'logs.export.requested', 'logs.export.completed', 'logs.export.failed',
  'logs.retention.completed', 'logs.retention.failed',
  'agent_update.requested', 'agent_update.claimed',
  'agent_update.download_started', 'agent_update.download_completed',
  'agent_update.manifest_verified', 'agent_update.package_hash_verified',
  'agent_update.package_hash_failed', 'agent_update.authenticode_verified',
  'agent_update.staged', 'agent_update.waiting_for_window',
  'agent_update.install_started', 'agent_update.service_stopped',
  'agent_update.files_replaced', 'agent_update.service_started',
  'agent_update.restarting', 'agent_update.verifying_health',
  'agent_update.health_verified', 'agent_update.completed', 'agent_update.failed',
  'agent_update.rollback_started', 'agent_update.rollback_completed',
  'agent_update.rollback_failed', 'agent_update.release_blocked',
] as const;

export type SystemEventType = (typeof SYSTEM_EVENT_TYPES)[number];

export const AGENT_EVENT_TYPES = [
  'sync.started', 'sync.completed', 'sync.failed', 'sync.retrying',
  'inventory.source.selected', 'inventory.source.conflict',
  'inventory.source.unavailable', 'inventory.zero_snapshot.confirmed',
  'inventory.zero_snapshot.rejected', 'service.started', 'service.stopping',
  'service.stopped', 'service.crashed', 'scheduler.started', 'scheduler.paused',
  'scheduler.resumed', 'jtl_connection.connected', 'jtl_connection.failed',
  'backend_connection.connected', 'backend_connection.failed',
  'agent_update.download_started', 'agent_update.download_completed',
  'agent_update.manifest_verified', 'agent_update.package_hash_verified',
  'agent_update.package_hash_failed', 'agent_update.authenticode_verified',
  'agent_update.staged', 'agent_update.install_started',
  'agent_update.service_stopped', 'agent_update.files_replaced',
  'agent_update.service_started', 'agent_update.health_verified',
  'agent_update.completed', 'agent_update.failed',
  'agent_update.rollback_started', 'agent_update.rollback_completed',
  'agent_update.rollback_failed', 'agent_update.release_blocked',
] as const;
