export const PERMISSIONS = {
  OVERVIEW_VIEW: 'overview.view',
  REVENUE_VIEW: 'revenue.view',
  DASHBOARD_VIEW: 'overview.view',
  SALES_VIEW: 'sales.view',
  ORDERS_VIEW: 'orders.view',
  SALES_EXPORT: 'sales.export',
  PRODUCTS_VIEW: 'products.view',
  PRODUCTS_EXPORT: 'products.export',
  INVENTORY_VIEW: 'inventory.view',
  CUSTOMERS_VIEW: 'customers.view',
  CUSTOMERS_EXPORT: 'customers.export',
  PAYMENTS_VIEW: 'payments.view',
  SHIPMENTS_VIEW: 'shipments.view',
  RETURNS_VIEW: 'returns.view',
  PLATFORMS_VIEW: 'platforms.view',
  PRODUCTION_VIEW: 'production.view',
  MARKETING_VIEW: 'marketing.view',
  REPORTS_VIEW: 'reports.view',
  SYNC_VIEW: 'sync.view',
  SYNC_MANAGE: 'sync.manage',
  SYNC_ROTATE_KEY: 'sync.rotate_key',
  SETTINGS_VIEW: 'settings.view',
  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',
  USERS_MANAGE: 'users.manage',
  ROLES_MANAGE: 'roles.manage',
  ADMIN_MANAGE: 'admin.manage',
  SETTINGS_MANAGE: 'settings.manage',
  PLATFORM_TENANTS_VIEW: 'platform.tenants.view',
  PLATFORM_TENANTS_MANAGE: 'platform.tenants.manage',
  PLATFORM_USERS_MANAGE: 'platform.users.manage',
  PLATFORM_AUDIT_VIEW: 'platform.audit.view',
  AUDIT_VIEW: 'audit.view',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_CATALOG: Array<{ key: PermissionKey; description: string }> = [
  { key: PERMISSIONS.OVERVIEW_VIEW, description: 'View dashboard overview' },
  { key: PERMISSIONS.REVENUE_VIEW, description: 'View revenue analytics' },
  { key: PERMISSIONS.SALES_VIEW, description: 'View sales analytics pages and APIs' },
  { key: PERMISSIONS.ORDERS_VIEW, description: 'View order analytics and lists' },
  { key: PERMISSIONS.SALES_EXPORT, description: 'Export sales analytics data' },
  { key: PERMISSIONS.PRODUCTS_VIEW, description: 'View product analytics pages and APIs' },
  { key: PERMISSIONS.PRODUCTS_EXPORT, description: 'Export product analytics data' },
  { key: PERMISSIONS.INVENTORY_VIEW, description: 'View inventory analytics pages and APIs' },
  { key: PERMISSIONS.CUSTOMERS_VIEW, description: 'View customer analytics pages and APIs' },
  { key: PERMISSIONS.CUSTOMERS_EXPORT, description: 'Export customer analytics data' },
  { key: PERMISSIONS.PAYMENTS_VIEW, description: 'View payment analytics' },
  { key: PERMISSIONS.SHIPMENTS_VIEW, description: 'View shipment analytics' },
  { key: PERMISSIONS.RETURNS_VIEW, description: 'View return analytics' },
  { key: PERMISSIONS.PLATFORMS_VIEW, description: 'View platform analytics' },
  { key: PERMISSIONS.PRODUCTION_VIEW, description: 'View production analytics' },
  { key: PERMISSIONS.MARKETING_VIEW, description: 'View marketing analytics' },
  { key: PERMISSIONS.REPORTS_VIEW, description: 'View reports' },
  { key: PERMISSIONS.SYNC_VIEW, description: 'View sync status and logs' },
  { key: PERMISSIONS.SYNC_MANAGE, description: 'Trigger and cancel manual sync jobs' },
  { key: PERMISSIONS.SYNC_ROTATE_KEY, description: 'Rotate sync API keys' },
  { key: PERMISSIONS.SETTINGS_VIEW, description: 'View settings' },
  { key: PERMISSIONS.USERS_VIEW, description: 'View tenant users' },
  { key: PERMISSIONS.USERS_CREATE, description: 'Create tenant users' },
  { key: PERMISSIONS.USERS_UPDATE, description: 'Update tenant users' },
  { key: PERMISSIONS.USERS_DELETE, description: 'Deactivate tenant users' },
  { key: PERMISSIONS.USERS_MANAGE, description: 'Manage tenant users' },
  { key: PERMISSIONS.ROLES_MANAGE, description: 'Grant and revoke user permissions' },
  { key: PERMISSIONS.ADMIN_MANAGE, description: 'Manage tenants, admins and platform configuration' },
  { key: PERMISSIONS.SETTINGS_MANAGE, description: 'Access and update account settings' },
  { key: PERMISSIONS.PLATFORM_TENANTS_VIEW, description: 'View platform tenants' },
  { key: PERMISSIONS.PLATFORM_TENANTS_MANAGE, description: 'Manage platform tenants' },
  { key: PERMISSIONS.PLATFORM_USERS_MANAGE, description: 'Manage platform users' },
  { key: PERMISSIONS.PLATFORM_AUDIT_VIEW, description: 'View platform audit logs' },
  { key: PERMISSIONS.AUDIT_VIEW, description: 'View security and audit trails' },
];

export const DEFAULT_ADMIN_PERMISSIONS: PermissionKey[] = [
  PERMISSIONS.OVERVIEW_VIEW,
  PERMISSIONS.REVENUE_VIEW,
  PERMISSIONS.SALES_VIEW,
  PERMISSIONS.ORDERS_VIEW,
  PERMISSIONS.SALES_EXPORT,
  PERMISSIONS.PRODUCTS_VIEW,
  PERMISSIONS.PRODUCTS_EXPORT,
  PERMISSIONS.INVENTORY_VIEW,
  PERMISSIONS.CUSTOMERS_VIEW,
  PERMISSIONS.CUSTOMERS_EXPORT,
  PERMISSIONS.PAYMENTS_VIEW,
  PERMISSIONS.SHIPMENTS_VIEW,
  PERMISSIONS.RETURNS_VIEW,
  PERMISSIONS.PLATFORMS_VIEW,
  PERMISSIONS.PRODUCTION_VIEW,
  PERMISSIONS.MARKETING_VIEW,
  PERMISSIONS.REPORTS_VIEW,
  PERMISSIONS.SYNC_VIEW,
  PERMISSIONS.SYNC_MANAGE,
  PERMISSIONS.SYNC_ROTATE_KEY,
  PERMISSIONS.SETTINGS_VIEW,
  PERMISSIONS.USERS_VIEW,
  PERMISSIONS.USERS_CREATE,
  PERMISSIONS.USERS_UPDATE,
  PERMISSIONS.USERS_DELETE,
  PERMISSIONS.USERS_MANAGE,
  PERMISSIONS.ROLES_MANAGE,
  PERMISSIONS.SETTINGS_MANAGE,
  PERMISSIONS.AUDIT_VIEW,
];

export const DEFAULT_USER_VIEWER_PERMISSIONS: PermissionKey[] = [
  PERMISSIONS.OVERVIEW_VIEW,
  PERMISSIONS.SALES_VIEW,
  PERMISSIONS.ORDERS_VIEW,
  PERMISSIONS.PRODUCTS_VIEW,
];

export const DEFAULT_USER_ANALYST_PERMISSIONS: PermissionKey[] = [
  ...DEFAULT_USER_VIEWER_PERMISSIONS,
  PERMISSIONS.SYNC_VIEW,
];

export const DEFAULT_USER_MANAGER_PERMISSIONS: PermissionKey[] = [
  PERMISSIONS.OVERVIEW_VIEW,
  PERMISSIONS.REVENUE_VIEW,
  PERMISSIONS.SALES_VIEW,
  PERMISSIONS.ORDERS_VIEW,
  PERMISSIONS.PRODUCTS_VIEW,
  PERMISSIONS.INVENTORY_VIEW,
  PERMISSIONS.CUSTOMERS_VIEW,
  PERMISSIONS.PAYMENTS_VIEW,
  PERMISSIONS.SHIPMENTS_VIEW,
  PERMISSIONS.RETURNS_VIEW,
];

export const PERMISSION_PRESETS = {
  SALES_USER: [
    PERMISSIONS.OVERVIEW_VIEW,
    PERMISSIONS.REVENUE_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.PRODUCTS_VIEW,
  ],
  INVENTORY_USER: [
    PERMISSIONS.OVERVIEW_VIEW,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.SHIPMENTS_VIEW,
  ],
  CUSTOMER_SUPPORT: [
    PERMISSIONS.OVERVIEW_VIEW,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.SHIPMENTS_VIEW,
    PERMISSIONS.RETURNS_VIEW,
  ],
  MANAGER: DEFAULT_USER_MANAGER_PERMISSIONS,
  COMPANY_ADMIN: [
    PERMISSIONS.OVERVIEW_VIEW,
    PERMISSIONS.REVENUE_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.SHIPMENTS_VIEW,
    PERMISSIONS.RETURNS_VIEW,
    PERMISSIONS.PLATFORMS_VIEW,
    PERMISSIONS.PRODUCTION_VIEW,
    PERMISSIONS.MARKETING_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.SYNC_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.SETTINGS_VIEW,
  ],
} as const satisfies Record<string, PermissionKey[]>;
