export const PERMISSIONS = {
  OVERVIEW_VIEW: 'overview.view',
  REVENUE_VIEW: 'revenue.view',
  DASHBOARD_VIEW: 'overview.view',
  SALES_VIEW: 'sales.view',
  ORDERS_VIEW: 'orders.view',
  SALES_EXPORT: 'sales.export',
  PRODUCTS_VIEW: 'products.view',
  PRODUCTS_EXPORT: 'products.export',
  INVENTORY_VIEW: 'inventory.view',
  CUSTOMERS_VIEW: 'customers.view',
  CUSTOMERS_EXPORT: 'customers.export',
  PAYMENTS_VIEW: 'payments.view',
  SHIPMENTS_VIEW: 'shipments.view',
  RETURNS_VIEW: 'returns.view',
  PLATFORMS_VIEW: 'platforms.view',
  PRODUCTION_VIEW: 'production.view',
  MARKETING_VIEW: 'marketing.view',
  REPORTS_VIEW: 'reports.view',
  SYNC_VIEW: 'sync.view',
  SYNC_MANAGE: 'sync.manage',
  SYNC_ROTATE_KEY: 'sync.rotate_key',
  SETTINGS_VIEW: 'settings.view',
  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',
  USERS_MANAGE: 'users.manage',
  ROLES_MANAGE: 'roles.manage',
  ADMIN_MANAGE: 'admin.manage',
  SETTINGS_MANAGE: 'settings.manage',
  PLATFORM_TENANTS_VIEW: 'platform.tenants.view',
  PLATFORM_TENANTS_MANAGE: 'platform.tenants.manage',
  PLATFORM_USERS_MANAGE: 'platform.users.manage',
  PLATFORM_AUDIT_VIEW: 'platform.audit.view',
  AUDIT_VIEW: 'audit.view',
  SYNC_STATUS_VIEW: 'sync.status.view',
  SYNC_HISTORY_VIEW: 'sync.history.view',
  SYNC_RUN_INCREMENTAL: 'sync.run.incremental',
  SYNC_RESYNC_INVENTORY: 'sync.resync.inventory',
  SYNC_RESYNC_PRODUCTS: 'sync.resync.products',
  SYNC_RESYNC_ORDERS: 'sync.resync.orders',
  SYNC_RESYNC_CUSTOMERS: 'sync.resync.customers',
  SYNC_RESYNC_FULL: 'sync.resync.full',
  SYNC_PAUSE: 'sync.pause',
  SYNC_RESUME: 'sync.resume',
  SYNC_CANCEL: 'sync.cancel',
  SYNC_DIAGNOSTICS: 'sync.diagnostics',
  SYNC_MANAGE_AGENTS: 'sync.manage_agents',
  SYNC_AGENT_UPDATE: 'sync.agent.update',
  SYNC_AGENT_UPDATE_MANAGE_RELEASES: 'sync.agent.update.manage_releases',
  SYNC_AGENT_UPDATE_RETRY_FAILED: 'sync.agent.update.retry_failed',
  LOGS_SYSTEM_VIEW: 'logs.system.view',
  LOGS_AUDIT_VIEW: 'logs.audit.view',
  LOGS_SECURITY_VIEW: 'logs.security.view',
  LOGS_EXPORT: 'logs.export',
  LOGS_STACKTRACE_VIEW: 'logs.stacktrace.view',
  LOGS_TENANT_VIEW: 'logs.tenant.view',
  AI_ANALYTICS_USE: 'ai.analytics.use',
  AI_SALES_VIEW: 'ai.sales.view',
  AI_PRODUCTS_VIEW: 'ai.products.view',
  AI_INVENTORY_VIEW: 'ai.inventory.view',
  AI_CUSTOMERS_AGGREGATE_VIEW: 'ai.customers.aggregate.view',
  AI_CUSTOMERS_DETAILS_VIEW: 'ai.customers.details.view',
  AI_OPERATIONS_VIEW: 'ai.operations.view',
  AI_LOGS_VIEW: 'ai.logs.view',
  AI_CONVERSATIONS_MANAGE: 'ai.conversations.manage',
  AI_FEEDBACK_SUBMIT: 'ai.feedback.submit',
  AI_ADMIN_VIEW_USAGE: 'ai.admin.view_usage',
  COMPARISON_VIEW: 'comparison.view',
  COMPARISON_SALES_VIEW: 'comparison.sales.view',
  COMPARISON_PRODUCTS_VIEW: 'comparison.products.view',
  COMPARISON_INVENTORY_VIEW: 'comparison.inventory.view',
  COMPARISON_CUSTOMERS_VIEW: 'comparison.customers.view',
  COMPARISON_EXPORT: 'comparison.export',
  COMPARISON_SAVED_VIEWS_MANAGE: 'comparison.saved_views.manage',
  COMPARISON_COST_MARGIN_VIEW: 'comparison.cost_margin.view',
  COMPARISON_CUSTOMER_DETAILS_VIEW: 'comparison.customer_details.view',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_CATALOG: Array<{ key: PermissionKey; description: string }> = [
  { key: PERMISSIONS.OVERVIEW_VIEW, description: 'View dashboard overview' },
  { key: PERMISSIONS.REVENUE_VIEW, description: 'View revenue analytics' },
  { key: PERMISSIONS.SALES_VIEW, description: 'View sales analytics pages and APIs' },
  { key: PERMISSIONS.ORDERS_VIEW, description: 'View order analytics and lists' },
  { key: PERMISSIONS.SALES_EXPORT, description: 'Export sales analytics data' },
  { key: PERMISSIONS.PRODUCTS_VIEW, description: 'View product analytics pages and APIs' },
  { key: PERMISSIONS.PRODUCTS_EXPORT, description: 'Export product analytics data' },
  { key: PERMISSIONS.INVENTORY_VIEW, description: 'View inventory analytics pages and APIs' },
  { key: PERMISSIONS.CUSTOMERS_VIEW, description: 'View customer analytics pages and APIs' },
  { key: PERMISSIONS.CUSTOMERS_EXPORT, description: 'Export customer analytics data' },
  { key: PERMISSIONS.PAYMENTS_VIEW, description: 'View payment analytics' },
  { key: PERMISSIONS.SHIPMENTS_VIEW, description: 'View shipment analytics' },
  { key: PERMISSIONS.RETURNS_VIEW, description: 'View return analytics' },
  { key: PERMISSIONS.PLATFORMS_VIEW, description: 'View platform analytics' },
  { key: PERMISSIONS.PRODUCTION_VIEW, description: 'View production analytics' },
  { key: PERMISSIONS.MARKETING_VIEW, description: 'View marketing analytics' },
  { key: PERMISSIONS.REPORTS_VIEW, description: 'View reports' },
  { key: PERMISSIONS.SYNC_VIEW, description: 'View sync status and logs' },
  { key: PERMISSIONS.SYNC_MANAGE, description: 'Trigger and cancel manual sync jobs' },
  { key: PERMISSIONS.SYNC_ROTATE_KEY, description: 'Rotate sync API keys' },
  { key: PERMISSIONS.SETTINGS_VIEW, description: 'View settings' },
  { key: PERMISSIONS.USERS_VIEW, description: 'View tenant users' },
  { key: PERMISSIONS.USERS_CREATE, description: 'Create tenant users' },
  { key: PERMISSIONS.USERS_UPDATE, description: 'Update tenant users' },
  { key: PERMISSIONS.USERS_DELETE, description: 'Deactivate tenant users' },
  { key: PERMISSIONS.USERS_MANAGE, description: 'Manage tenant users' },
  { key: PERMISSIONS.ROLES_MANAGE, description: 'Grant and revoke user permissions' },
  { key: PERMISSIONS.ADMIN_MANAGE, description: 'Manage tenants, admins and platform configuration' },
  { key: PERMISSIONS.SETTINGS_MANAGE, description: 'Access and update account settings' },
  { key: PERMISSIONS.PLATFORM_TENANTS_VIEW, description: 'View platform tenants' },
  { key: PERMISSIONS.PLATFORM_TENANTS_MANAGE, description: 'Manage platform tenants' },
  { key: PERMISSIONS.PLATFORM_USERS_MANAGE, description: 'Manage platform users' },
  { key: PERMISSIONS.PLATFORM_AUDIT_VIEW, description: 'View platform audit logs' },
  { key: PERMISSIONS.AUDIT_VIEW, description: 'View security and audit trails' },
  { key: PERMISSIONS.SYNC_STATUS_VIEW, description: 'View live sync agent status' },
  { key: PERMISSIONS.SYNC_HISTORY_VIEW, description: 'View sync command history' },
  { key: PERMISSIONS.SYNC_RUN_INCREMENTAL, description: 'Queue incremental sync commands' },
  { key: PERMISSIONS.SYNC_RESYNC_INVENTORY, description: 'Queue inventory resync commands' },
  { key: PERMISSIONS.SYNC_RESYNC_PRODUCTS, description: 'Queue product resync commands' },
  { key: PERMISSIONS.SYNC_RESYNC_ORDERS, description: 'Queue order resync commands' },
  { key: PERMISSIONS.SYNC_RESYNC_CUSTOMERS, description: 'Queue customer resync commands' },
  { key: PERMISSIONS.SYNC_RESYNC_FULL, description: 'Queue full resync commands' },
  { key: PERMISSIONS.SYNC_PAUSE, description: 'Pause scheduled synchronization' },
  { key: PERMISSIONS.SYNC_RESUME, description: 'Resume scheduled synchronization' },
  { key: PERMISSIONS.SYNC_CANCEL, description: 'Cancel active sync commands' },
  { key: PERMISSIONS.SYNC_DIAGNOSTICS, description: 'Run sync diagnostics' },
  { key: PERMISSIONS.SYNC_MANAGE_AGENTS, description: 'Manage sync agents' },
  { key: PERMISSIONS.SYNC_AGENT_UPDATE, description: 'Request approved sync-agent updates' },
  { key: PERMISSIONS.SYNC_AGENT_UPDATE_MANAGE_RELEASES, description: 'Manage sync-agent releases' },
  { key: PERMISSIONS.SYNC_AGENT_UPDATE_RETRY_FAILED, description: 'Retry failed sync-agent updates' },
  { key: PERMISSIONS.LOGS_SYSTEM_VIEW, description: 'View system events' },
  { key: PERMISSIONS.LOGS_AUDIT_VIEW, description: 'View tenant audit events' },
  { key: PERMISSIONS.LOGS_SECURITY_VIEW, description: 'View security events' },
  { key: PERMISSIONS.LOGS_EXPORT, description: 'Export filtered logs' },
  { key: PERMISSIONS.LOGS_STACKTRACE_VIEW, description: 'View protected diagnostic detail' },
  { key: PERMISSIONS.LOGS_TENANT_VIEW, description: 'View tenant-scoped logs' },
  { key: PERMISSIONS.AI_ANALYTICS_USE, description: 'Use Analytics Copilot' },
  { key: PERMISSIONS.AI_SALES_VIEW, description: 'Use sales Copilot tools' },
  { key: PERMISSIONS.AI_PRODUCTS_VIEW, description: 'Use product Copilot tools' },
  { key: PERMISSIONS.AI_INVENTORY_VIEW, description: 'Use inventory Copilot tools' },
  { key: PERMISSIONS.AI_CUSTOMERS_AGGREGATE_VIEW, description: 'Use aggregate customer Copilot tools' },
  { key: PERMISSIONS.AI_CUSTOMERS_DETAILS_VIEW, description: 'Use customer detail Copilot tools' },
  { key: PERMISSIONS.AI_OPERATIONS_VIEW, description: 'Use operations Copilot tools' },
  { key: PERMISSIONS.AI_LOGS_VIEW, description: 'Use logs Copilot tools' },
  { key: PERMISSIONS.AI_CONVERSATIONS_MANAGE, description: 'Manage Copilot conversations' },
  { key: PERMISSIONS.AI_FEEDBACK_SUBMIT, description: 'Submit Copilot feedback' },
  { key: PERMISSIONS.AI_ADMIN_VIEW_USAGE, description: 'View Copilot usage' },
  { key: PERMISSIONS.COMPARISON_VIEW, description: 'View Compare and Analyse' },
  { key: PERMISSIONS.COMPARISON_SALES_VIEW, description: 'View channel and sales comparisons' },
  { key: PERMISSIONS.COMPARISON_PRODUCTS_VIEW, description: 'View product comparisons' },
  { key: PERMISSIONS.COMPARISON_INVENTORY_VIEW, description: 'View inventory comparisons' },
  { key: PERMISSIONS.COMPARISON_CUSTOMERS_VIEW, description: 'View customer comparisons' },
  { key: PERMISSIONS.COMPARISON_EXPORT, description: 'Export comparison data' },
  { key: PERMISSIONS.COMPARISON_SAVED_VIEWS_MANAGE, description: 'Manage saved comparison views' },
  { key: PERMISSIONS.COMPARISON_COST_MARGIN_VIEW, description: 'View comparison cost and margin metrics' },
  { key: PERMISSIONS.COMPARISON_CUSTOMER_DETAILS_VIEW, description: 'View comparison customer details' },
];

export const DEFAULT_ADMIN_PERMISSIONS: PermissionKey[] = [
  PERMISSIONS.OVERVIEW_VIEW,
  PERMISSIONS.REVENUE_VIEW,
  PERMISSIONS.SALES_VIEW,
  PERMISSIONS.ORDERS_VIEW,
  PERMISSIONS.SALES_EXPORT,
  PERMISSIONS.PRODUCTS_VIEW,
  PERMISSIONS.PRODUCTS_EXPORT,
  PERMISSIONS.INVENTORY_VIEW,
  PERMISSIONS.CUSTOMERS_VIEW,
  PERMISSIONS.CUSTOMERS_EXPORT,
  PERMISSIONS.PAYMENTS_VIEW,
  PERMISSIONS.SHIPMENTS_VIEW,
  PERMISSIONS.RETURNS_VIEW,
  PERMISSIONS.PLATFORMS_VIEW,
  PERMISSIONS.PRODUCTION_VIEW,
  PERMISSIONS.MARKETING_VIEW,
  PERMISSIONS.REPORTS_VIEW,
  PERMISSIONS.SYNC_VIEW,
  PERMISSIONS.SYNC_MANAGE,
  PERMISSIONS.SYNC_ROTATE_KEY,
  PERMISSIONS.SETTINGS_VIEW,
  PERMISSIONS.USERS_VIEW,
  PERMISSIONS.USERS_CREATE,
  PERMISSIONS.USERS_UPDATE,
  PERMISSIONS.USERS_DELETE,
  PERMISSIONS.USERS_MANAGE,
  PERMISSIONS.ROLES_MANAGE,
  PERMISSIONS.SETTINGS_MANAGE,
  PERMISSIONS.AUDIT_VIEW,
  PERMISSIONS.SYNC_STATUS_VIEW,
  PERMISSIONS.SYNC_HISTORY_VIEW,
  PERMISSIONS.SYNC_RUN_INCREMENTAL,
  PERMISSIONS.SYNC_RESYNC_INVENTORY,
  PERMISSIONS.SYNC_RESYNC_PRODUCTS,
  PERMISSIONS.SYNC_RESYNC_ORDERS,
  PERMISSIONS.SYNC_RESYNC_CUSTOMERS,
  PERMISSIONS.SYNC_RESYNC_FULL,
  PERMISSIONS.SYNC_PAUSE,
  PERMISSIONS.SYNC_RESUME,
  PERMISSIONS.SYNC_CANCEL,
  PERMISSIONS.SYNC_DIAGNOSTICS,
  PERMISSIONS.SYNC_MANAGE_AGENTS,
  PERMISSIONS.SYNC_AGENT_UPDATE,
  PERMISSIONS.SYNC_AGENT_UPDATE_MANAGE_RELEASES,
  PERMISSIONS.SYNC_AGENT_UPDATE_RETRY_FAILED,
  PERMISSIONS.LOGS_SYSTEM_VIEW,
  PERMISSIONS.LOGS_AUDIT_VIEW,
  PERMISSIONS.LOGS_SECURITY_VIEW,
  PERMISSIONS.LOGS_EXPORT,
  PERMISSIONS.LOGS_STACKTRACE_VIEW,
  PERMISSIONS.LOGS_TENANT_VIEW,
  PERMISSIONS.AI_ANALYTICS_USE,
  PERMISSIONS.AI_SALES_VIEW,
  PERMISSIONS.AI_PRODUCTS_VIEW,
  PERMISSIONS.AI_INVENTORY_VIEW,
  PERMISSIONS.AI_CUSTOMERS_AGGREGATE_VIEW,
  PERMISSIONS.AI_OPERATIONS_VIEW,
  PERMISSIONS.AI_LOGS_VIEW,
  PERMISSIONS.AI_CONVERSATIONS_MANAGE,
  PERMISSIONS.AI_FEEDBACK_SUBMIT,
  PERMISSIONS.AI_ADMIN_VIEW_USAGE,
  PERMISSIONS.COMPARISON_VIEW,
  PERMISSIONS.COMPARISON_SALES_VIEW,
  PERMISSIONS.COMPARISON_PRODUCTS_VIEW,
  PERMISSIONS.COMPARISON_INVENTORY_VIEW,
  PERMISSIONS.COMPARISON_CUSTOMERS_VIEW,
  PERMISSIONS.COMPARISON_EXPORT,
  PERMISSIONS.COMPARISON_SAVED_VIEWS_MANAGE,
  PERMISSIONS.COMPARISON_COST_MARGIN_VIEW,
  PERMISSIONS.COMPARISON_CUSTOMER_DETAILS_VIEW,
];

export const DEFAULT_USER_VIEWER_PERMISSIONS: PermissionKey[] = [
  PERMISSIONS.OVERVIEW_VIEW,
  PERMISSIONS.SALES_VIEW,
  PERMISSIONS.ORDERS_VIEW,
  PERMISSIONS.PRODUCTS_VIEW,
];

export const DEFAULT_USER_ANALYST_PERMISSIONS: PermissionKey[] = [
  ...DEFAULT_USER_VIEWER_PERMISSIONS,
  PERMISSIONS.SYNC_VIEW,
  PERMISSIONS.COMPARISON_VIEW,
  PERMISSIONS.COMPARISON_SALES_VIEW,
  PERMISSIONS.COMPARISON_PRODUCTS_VIEW,
  PERMISSIONS.COMPARISON_INVENTORY_VIEW,
  PERMISSIONS.COMPARISON_CUSTOMERS_VIEW,
];

export const DEFAULT_USER_MANAGER_PERMISSIONS: PermissionKey[] = [
  PERMISSIONS.OVERVIEW_VIEW,
  PERMISSIONS.REVENUE_VIEW,
  PERMISSIONS.SALES_VIEW,
  PERMISSIONS.ORDERS_VIEW,
  PERMISSIONS.PRODUCTS_VIEW,
  PERMISSIONS.INVENTORY_VIEW,
  PERMISSIONS.CUSTOMERS_VIEW,
  PERMISSIONS.PAYMENTS_VIEW,
  PERMISSIONS.SHIPMENTS_VIEW,
  PERMISSIONS.RETURNS_VIEW,
  PERMISSIONS.COMPARISON_VIEW,
  PERMISSIONS.COMPARISON_SALES_VIEW,
  PERMISSIONS.COMPARISON_PRODUCTS_VIEW,
  PERMISSIONS.COMPARISON_INVENTORY_VIEW,
  PERMISSIONS.COMPARISON_CUSTOMERS_VIEW,
  PERMISSIONS.COMPARISON_EXPORT,
  PERMISSIONS.COMPARISON_SAVED_VIEWS_MANAGE,
];

export const PERMISSION_PRESETS = {
  SALES_USER: [
    PERMISSIONS.OVERVIEW_VIEW,
    PERMISSIONS.REVENUE_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.PRODUCTS_VIEW,
  ],
  INVENTORY_USER: [
    PERMISSIONS.OVERVIEW_VIEW,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.SHIPMENTS_VIEW,
  ],
  CUSTOMER_SUPPORT: [
    PERMISSIONS.OVERVIEW_VIEW,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.SHIPMENTS_VIEW,
    PERMISSIONS.RETURNS_VIEW,
  ],
  MANAGER: DEFAULT_USER_MANAGER_PERMISSIONS,
  COMPANY_ADMIN: [
    PERMISSIONS.OVERVIEW_VIEW,
    PERMISSIONS.REVENUE_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.SHIPMENTS_VIEW,
    PERMISSIONS.RETURNS_VIEW,
    PERMISSIONS.PLATFORMS_VIEW,
    PERMISSIONS.PRODUCTION_VIEW,
    PERMISSIONS.MARKETING_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.SYNC_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.SETTINGS_VIEW,
  ],
} as const satisfies Record<string, PermissionKey[]>;
