import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

export const FEATURE_FLAGS = [
  'SYNC_CONTROL_HEARTBEAT_ENABLED', 'SYNC_CONTROL_STATUS_ENABLED',
  'SYNC_CONTROL_COMMANDS_ENABLED', 'SYNC_CONTROL_ADVANCED_COMMANDS_ENABLED',
  'SYNC_CONTROL_MODULE_RESYNC_ENABLED', 'SYNC_CONTROL_ALLOW_OFFLINE_QUEUE',
  'SYSTEM_LOGS_ENABLED', 'SYSTEM_LOGS_EXPORT_ENABLED',
  'SYSTEM_LOGS_API_ENABLED', 'SYSTEM_LOGS_UI_ENABLED',
  'SYSTEM_LOGS_AGENT_EVENTS_ENABLED', 'SYSTEM_LOGS_SECURITY_TAB_ENABLED',
  'SYSTEM_LOGS_RETENTION_ENABLED',
  'AI_ANALYTICS_ENABLED', 'AI_ANALYTICS_SALES_ENABLED',
  'AI_ANALYTICS_OPERATIONS_ENABLED', 'AI_ANALYTICS_LOGS_ENABLED',
  'ANALYTICS_COPILOT_DATA_ENABLED',
  'COMPARISON_CENTRE_ENABLED', 'COMPARISON_CHANNEL_DRILLDOWN_ENABLED',
  'COMPARISON_PRODUCT_PERFORMANCE_ENABLED',
  'COMPARISON_INVENTORY_PERFORMANCE_ENABLED',
  'COMPARISON_CUSTOMER_ANALYSIS_ENABLED',
  'SYNC_AGENT_UPDATE_ENABLED', 'SYNC_AGENT_UPDATE_REQUEST_ENABLED',
  'SYNC_AGENT_AUTO_UPDATE_ENABLED', 'SYNC_AGENT_RELEASE_MANAGEMENT_ENABLED',
  'MARKETPLACE_PLATFORM_ENABLED', 'MARKETPLACE_ACCOUNT_API_ENABLED',
  'MARKETPLACE_QUEUE_ENABLED', 'MARKETPLACE_SCHEDULER_ENABLED',
  'MARKETPLACE_REALTIME_WORKER_ENABLED', 'MARKETPLACE_BULK_WORKER_ENABLED',
  'MARKETPLACE_POSTPROCESS_WORKER_ENABLED', 'MARKETPLACE_CANONICAL_READS_ENABLED',
  'MARKETPLACE_WRITE_ACTIONS_ENABLED', 'MARKETPLACE_MOCK_CONNECTOR_ENABLED',
  'MARKETPLACE_REVIEWS_ENABLED', 'MARKETPLACE_AMAZON_REAL_CONNECTOR_ENABLED',
  'MARKETPLACE_AMAZON_CUSTOMER_FEEDBACK_ENABLED', 'MARKETPLACE_AMAZON_REVIEW_INSIGHTS_ENABLED',
  'MARKETPLACE_AMAZON_REVIEW_TRENDS_ENABLED', 'MARKETPLACE_AMAZON_EXTERNAL_REVIEWS_ENABLED',
  'MARKETPLACE_EBAY_FEEDBACK_ENABLED', 'MARKETPLACE_EBAY_PRODUCT_RATINGS_ENABLED',
  'MARKETPLACE_KAUFLAND_SUPPORT_FEEDBACK_ENABLED', 'MARKETPLACE_KAUFLAND_EXTERNAL_REVIEWS_ENABLED',
  'MARKETPLACE_OTTO_EXTERNAL_REVIEWS_ENABLED', 'MARKETPLACE_MEDIAMARKT_ORDER_EVALUATIONS_ENABLED',
  'MARKETPLACE_MEDIAMARKT_EXTERNAL_REVIEWS_ENABLED',
] as const;
export type FeatureFlag = (typeof FEATURE_FLAGS)[number];

@Injectable()
export class PlatformConfigService {
  constructor(private readonly config: ConfigService) {}
  enabled(flag: FeatureFlag): boolean {
    const defaults: Partial<Record<FeatureFlag, boolean>> = {
      SYNC_CONTROL_HEARTBEAT_ENABLED: true,
      SYNC_CONTROL_STATUS_ENABLED: true,
      SYNC_CONTROL_ALLOW_OFFLINE_QUEUE: true,
      COMPARISON_CENTRE_ENABLED: true,
      COMPARISON_CHANNEL_DRILLDOWN_ENABLED: true,
      COMPARISON_PRODUCT_PERFORMANCE_ENABLED: true,
      COMPARISON_INVENTORY_PERFORMANCE_ENABLED: true,
      COMPARISON_CUSTOMER_ANALYSIS_ENABLED: true,
      MARKETPLACE_PLATFORM_ENABLED: true,
      MARKETPLACE_ACCOUNT_API_ENABLED: true,
    };
    const raw = this.config.get<string>(flag);
    return raw == null || raw === '' ? defaults[flag] ?? false : raw.trim().toLowerCase() === 'true';
  }
  publicFlags() {
    return Object.fromEntries(FEATURE_FLAGS.map((flag) => [flag, this.enabled(flag)]));
  }

  integer(name: string, fallback: number, minimum: number, maximum: number): number {
    const raw = Number.parseInt(this.config.get<string>(name, String(fallback)), 10);
    return Number.isFinite(raw) ? Math.min(maximum, Math.max(minimum, raw)) : fallback;
  }
}
